#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Apr 05, 2021 08:32:24 PM CEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global respi
    respi = tk.IntVar()
    global conscience
    conscience = tk.IntVar()
    global inter
    inter = tk.IntVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def fc():
    print('layout_support.fc')
    sys.stdout.flush()

def fr():
    print('layout_support.fr')
    sys.stdout.flush()

def sat():
    print('layout_support.sat')
    sys.stdout.flush()

def tad():
    print('layout_support.tad')
    sys.stdout.flush()

def tag():
    print('layout_support.tag')
    sys.stdout.flush()

def trc():
    print('layout_support.trc')
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import layout
    layout.vp_start_gui()




