#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Apr 05, 2021 06:03:43 PM CEST  platform: Windows NT

import sys, random, math
from datetime import datetime
from tkinter import font
import tkinter.font as tkFont
from tkinter.constants import DISABLED, SOLID

all_index = 1.0
SIZE_FONT = 20

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import layout_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    layout_support.set_Tk_var()
    top = Toplevel1 (root)
    layout_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    layout_support.set_Tk_var()
    top = Toplevel1 (w)
    layout_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):


# MES FONCTIONS

        def insert_all_text(text):
                global all_index
                all_index += 1
                now = datetime.now() # current date and time
                date_time = now.strftime("%H:%M:%S > ")	
                self.all_text.insert(all_index, date_time + text + '\n')

        def tad():
                a_list = [7,8,9,10,11,12,13,14,15,16,17,18,19]
                distribution = [0.00326 , 0.00652 , 0.0125 , 0.025 , 0.15 , 0.5 , 0.15 , 0.075 , 0.0375 , 0.0175 , 0.015 , 0.003 , 0.00146]
                random_number = random.choices(a_list, distribution)
                random_number = int(str(random_number)[1:-1])
                print(random_number)
                random_number2 = int(((random_number/2)*10 + 10) + random.randint(0,9))
                random_number = random_number*10 + random.randint(0,9)
                tension = str(random_number) + "/" + str(random_number2)
                tension2 = "Mesure de la tension artérielle bras droit : " + str(random_number) + "/" + str(random_number2)
                self.tad_text.delete(1.0,"end")
                self.tad_text.insert(1.0, tension)
                insert_all_text(tension2)

        def tag():
                a_list = [7,8,9,10,11,12,13,14,15,16,17,18,19]
                distribution = [0.00326 , 0.00652 , 0.0125 , 0.025 , 0.15 , 0.5 , 0.15 , 0.075 , 0.0375 , 0.0175 , 0.015 , 0.003 , 0.00146]
                random_number = random.choices(a_list, distribution)
                random_number = int(str(random_number)[1:-1])
                print(random_number)
                random_number2 = int(((random_number/2)*10 + 10) + random.randint(0,9))
                random_number = random_number*10 + random.randint(0,9)
                tension = str(random_number) + "/" + str(random_number2)
                tension2 = "Mesure de la tension artérielle bras gauche : " + str(random_number) + "/" + str(random_number2)
                self.tag_text.delete(1.0,"end")
                self.tag_text.insert(1.0, tension)
                insert_all_text(tension2)

       #mesure fréquence cardiaque
        def fc():
                print('layout_support.fc')
                sys.stdout.flush()

        #mesure fréquence respiratoire
        def fr():
                print('layout_support.fr')
                sys.stdout.flush()

        #mesure saturation pulsatile o2
        def sat():
                print('layout_support.sat')
                sys.stdout.flush()

        # mesure trc
        def trc():
                print('layout_support.trc')
                sys.stdout.flush()

        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("663x1047+625+84")
        top.minsize(120, 1)
        top.maxsize(4484, 1421)
        top.resizable(1,  1)
        top.title("Projet EMS RP - Gyrfalcon v1.0 BETA")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.015, rely=0.086, relheight=0.904
                , relwidth=0.964)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.respiration = tk.LabelFrame(self.Frame1)
        self.respiration.place(relx=0.485, rely=0.116, relheight=0.079
                , relwidth=0.485)
        self.respiration.configure(relief='groove')
        self.respiration.configure(foreground="black")
        self.respiration.configure(text='''RESPIRATION''')
        self.respiration.configure(background="#d9d9d9")
        self.respiration.configure(highlightbackground="#d9d9d9")
        self.respiration.configure(highlightcolor="black")

        self.Radiobutton3 = tk.Radiobutton(self.respiration)
        self.Radiobutton3.place(relx=0.194, rely=0.4, relheight=0.333
                , relwidth=0.187, bordermode='ignore')
        self.Radiobutton3.configure(activebackground="#ececec")
        self.Radiobutton3.configure(activeforeground="#000000")
        self.Radiobutton3.configure(background="#d9d9d9")
        self.Radiobutton3.configure(disabledforeground="#a3a3a3")
        self.Radiobutton3.configure(foreground="#000000")
        self.Radiobutton3.configure(highlightbackground="#d9d9d9")
        self.Radiobutton3.configure(highlightcolor="black")
        self.Radiobutton3.configure(justify='left')
        self.Radiobutton3.configure(text='''OUI''')
        self.Radiobutton3.configure(value="1")
        self.Radiobutton3.configure(variable=layout_support.respi)

        self.Radiobutton4 = tk.Radiobutton(self.respiration)
        self.Radiobutton4.place(relx=0.548, rely=0.4, relheight=0.333
                , relwidth=0.187, bordermode='ignore')
        self.Radiobutton4.configure(activebackground="#ececec")
        self.Radiobutton4.configure(activeforeground="#000000")
        self.Radiobutton4.configure(background="#d9d9d9")
        self.Radiobutton4.configure(disabledforeground="#a3a3a3")
        self.Radiobutton4.configure(foreground="#000000")
        self.Radiobutton4.configure(highlightbackground="#d9d9d9")
        self.Radiobutton4.configure(highlightcolor="black")
        self.Radiobutton4.configure(justify='left')
        self.Radiobutton4.configure(text='''NON''')
        self.Radiobutton4.configure(value="0")
        self.Radiobutton4.configure(variable=layout_support.respi)

        self.conscience = tk.LabelFrame(self.Frame1)
        self.conscience.place(relx=0.031, rely=0.116, relheight=0.079
                , relwidth=0.438)
        self.conscience.configure(relief='groove')
        self.conscience.configure(foreground="black")
        self.conscience.configure(text='''CONSCIENCE''')
        self.conscience.configure(background="#d9d9d9")
        self.conscience.configure(highlightbackground="#d9d9d9")
        self.conscience.configure(highlightcolor="black")

        self.Radiobutton1 = tk.Radiobutton(self.conscience)
        self.Radiobutton1.place(relx=0.214, rely=0.4, relheight=0.333
                , relwidth=0.207, bordermode='ignore')
        self.Radiobutton1.configure(activebackground="#ececec")
        self.Radiobutton1.configure(activeforeground="#000000")
        self.Radiobutton1.configure(background="#d9d9d9")
        self.Radiobutton1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1.configure(foreground="#000000")
        self.Radiobutton1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1.configure(highlightcolor="black")
        self.Radiobutton1.configure(justify='left')
        self.Radiobutton1.configure(text='''OUI''')
        self.Radiobutton1.configure(value="1")
        self.Radiobutton1.configure(variable=layout_support.conscience)

        self.Radiobutton2 = tk.Radiobutton(self.conscience)
        self.Radiobutton2.place(relx=0.607, rely=0.4, relheight=0.333
                , relwidth=0.207, bordermode='ignore')
        self.Radiobutton2.configure(activebackground="#ececec")
        self.Radiobutton2.configure(activeforeground="#000000")
        self.Radiobutton2.configure(background="#d9d9d9")
        self.Radiobutton2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2.configure(foreground="#000000")
        self.Radiobutton2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2.configure(highlightcolor="black")
        self.Radiobutton2.configure(justify='left')
        self.Radiobutton2.configure(text='''NON''')
        self.Radiobutton2.configure(value="0")
        self.Radiobutton2.configure(variable=layout_support.conscience)

        self.intervention = tk.LabelFrame(self.Frame1)
        self.intervention.place(relx=0.031, rely=0.011, relheight=0.091
                , relwidth=0.939)
        self.intervention.configure(relief='groove')
        self.intervention.configure(foreground="black")
        self.intervention.configure(text='''INTERVENTION''')
        self.intervention.configure(background="#d9d9d9")
        self.intervention.configure(highlightbackground="#d9d9d9")
        self.intervention.configure(highlightcolor="black")

        self.Radiobutton5 = tk.Radiobutton(self.intervention)
        self.Radiobutton5.place(relx=0.033, rely=0.349, relheight=0.291
                , relwidth=0.113, bordermode='ignore')
        self.Radiobutton5.configure(activebackground="#ececec")
        self.Radiobutton5.configure(activeforeground="#000000")
        self.Radiobutton5.configure(background="#d9d9d9")
        self.Radiobutton5.configure(disabledforeground="#a3a3a3")
        self.Radiobutton5.configure(foreground="#000000")
        self.Radiobutton5.configure(highlightbackground="#d9d9d9")
        self.Radiobutton5.configure(highlightcolor="black")
        self.Radiobutton5.configure(justify='left')
        self.Radiobutton5.configure(text='''Malaise''')
        self.Radiobutton5.configure(value="0")
        self.Radiobutton5.configure(variable=layout_support.inter)

        self.Radiobutton6 = tk.Radiobutton(self.intervention)
        self.Radiobutton6.place(relx=0.183, rely=0.349, relheight=0.291
                , relwidth=0.163, bordermode='ignore')
        self.Radiobutton6.configure(activebackground="#ececec")
        self.Radiobutton6.configure(activeforeground="#000000")
        self.Radiobutton6.configure(background="#d9d9d9")
        self.Radiobutton6.configure(disabledforeground="#a3a3a3")
        self.Radiobutton6.configure(foreground="#000000")
        self.Radiobutton6.configure(highlightbackground="#d9d9d9")
        self.Radiobutton6.configure(highlightcolor="black")
        self.Radiobutton6.configure(justify='left')
        self.Radiobutton6.configure(text='''Plaie simple''')
        self.Radiobutton6.configure(value="1")
        self.Radiobutton6.configure(variable=layout_support.inter)

        self.Radiobutton7 = tk.Radiobutton(self.intervention)
        self.Radiobutton7.place(relx=0.75, rely=0.233, relheight=0.291
                , relwidth=0.213, bordermode='ignore')
        self.Radiobutton7.configure(activebackground="#ececec")
        self.Radiobutton7.configure(activeforeground="#000000")
        self.Radiobutton7.configure(background="#d9d9d9")
        self.Radiobutton7.configure(disabledforeground="#a3a3a3")
        self.Radiobutton7.configure(foreground="#000000")
        self.Radiobutton7.configure(highlightbackground="#d9d9d9")
        self.Radiobutton7.configure(highlightcolor="black")
        self.Radiobutton7.configure(justify='left')
        self.Radiobutton7.configure(text='''Plaie arme blanche''')
        self.Radiobutton7.configure(value="2")
        self.Radiobutton7.configure(variable=layout_support.inter)

        self.Radiobutton8 = tk.Radiobutton(self.intervention)
        self.Radiobutton8.place(relx=0.733, rely=0.581, relheight=0.291
                , relwidth=0.213, bordermode='ignore')
        self.Radiobutton8.configure(activebackground="#ececec")
        self.Radiobutton8.configure(activeforeground="#000000")
        self.Radiobutton8.configure(background="#d9d9d9")
        self.Radiobutton8.configure(disabledforeground="#a3a3a3")
        self.Radiobutton8.configure(foreground="#000000")
        self.Radiobutton8.configure(highlightbackground="#d9d9d9")
        self.Radiobutton8.configure(highlightcolor="black")
        self.Radiobutton8.configure(justify='left')
        self.Radiobutton8.configure(text='''Plaie arme à feu''')
        self.Radiobutton8.configure(value="3")
        self.Radiobutton8.configure(variable=layout_support.inter)

        self.Radiobutton9 = tk.Radiobutton(self.intervention)
        self.Radiobutton9.place(relx=0.383, rely=0.349, relheight=0.291
                , relwidth=0.097, bordermode='ignore')
        self.Radiobutton9.configure(activebackground="#ececec")
        self.Radiobutton9.configure(activeforeground="#000000")
        self.Radiobutton9.configure(background="#d9d9d9")
        self.Radiobutton9.configure(disabledforeground="#a3a3a3")
        self.Radiobutton9.configure(foreground="#000000")
        self.Radiobutton9.configure(highlightbackground="#d9d9d9")
        self.Radiobutton9.configure(highlightcolor="black")
        self.Radiobutton9.configure(justify='left')
        self.Radiobutton9.configure(text='''AVP''')
        self.Radiobutton9.configure(value="4")
        self.Radiobutton9.configure(variable=layout_support.inter)

        self.Radiobutton10 = tk.Radiobutton(self.intervention)
        self.Radiobutton10.place(relx=0.517, rely=0.349, relheight=0.291
                , relwidth=0.163, bordermode='ignore')
        self.Radiobutton10.configure(activebackground="#ececec")
        self.Radiobutton10.configure(activeforeground="#000000")
        self.Radiobutton10.configure(background="#d9d9d9")
        self.Radiobutton10.configure(disabledforeground="#a3a3a3")
        self.Radiobutton10.configure(foreground="#000000")
        self.Radiobutton10.configure(highlightbackground="#d9d9d9")
        self.Radiobutton10.configure(highlightcolor="black")
        self.Radiobutton10.configure(justify='left')
        self.Radiobutton10.configure(text='''Traumatisme''')
        self.Radiobutton10.configure(value="5")
        self.Radiobutton10.configure(variable=layout_support.inter)

        self.bilanrespi = tk.LabelFrame(self.Frame1)
        self.bilanrespi.place(relx=0.031, rely=0.211, relheight=0.152
                , relwidth=0.939)
        self.bilanrespi.configure(relief='groove')
        self.bilanrespi.configure(foreground="black")
        self.bilanrespi.configure(text='''BILAN RESPIRATOIRE''')
        self.bilanrespi.configure(background="#d9d9d9")
        self.bilanrespi.configure(highlightbackground="#d9d9d9")
        self.bilanrespi.configure(highlightcolor="black")

        self.sat_button = tk.Button(self.bilanrespi)
        self.sat_button.place(relx=0.033, rely=0.208, height=64, width=127
                , bordermode='ignore')
        self.sat_button.configure(activebackground="#ececec")
        self.sat_button.configure(activeforeground="#000000")
        self.sat_button.configure(background="#d9d9d9")
        self.sat_button.configure(command=sat)
        self.sat_button.configure(disabledforeground="#a3a3a3")
        self.sat_button.configure(foreground="#000000")
        self.sat_button.configure(highlightbackground="#d9d9d9")
        self.sat_button.configure(highlightcolor="black")
        self.sat_button.configure(pady="0")
        self.sat_button.configure(text='''MESURE SAT''')

        self.fr_button = tk.Button(self.bilanrespi)
        self.fr_button.place(relx=0.283, rely=0.208, height=64, width=127
                , bordermode='ignore')
        self.fr_button.configure(activebackground="#ececec")
        self.fr_button.configure(activeforeground="#000000")
        self.fr_button.configure(background="#d9d9d9")
        self.fr_button.configure(command=fr)
        self.fr_button.configure(disabledforeground="#a3a3a3")
        self.fr_button.configure(foreground="#000000")
        self.fr_button.configure(highlightbackground="#d9d9d9")
        self.fr_button.configure(highlightcolor="black")
        self.fr_button.configure(pady="0")
        self.fr_button.configure(text='''MESURE FR''')

        self.sat_text = tk.Text(self.bilanrespi)
        self.sat_text.place(relx=0.033, rely=0.694, relheight=0.236
                , relwidth=0.212, bordermode='ignore')
        self.sat_text.configure(background="white")
        self.sat_text.configure(font=("TkTextFont", SIZE_FONT))
        self.sat_text.configure(foreground="black")
        self.sat_text.configure(highlightbackground="#d9d9d9")
        self.sat_text.configure(highlightcolor="black")
        self.sat_text.configure(insertbackground="black")
        self.sat_text.configure(selectbackground="blue")
        self.sat_text.configure(selectforeground="white")
        self.sat_text.configure(wrap="word")

        self.fr_text = tk.Text(self.bilanrespi)
        self.fr_text.place(relx=0.283, rely=0.694, relheight=0.236
                , relwidth=0.212, bordermode='ignore')
        self.fr_text.configure(background="white")
        self.fr_text.configure(font=("TkTextFont", SIZE_FONT))
        self.fr_text.configure(foreground="black")
        self.fr_text.configure(highlightbackground="#d9d9d9")
        self.fr_text.configure(highlightcolor="black")
        self.fr_text.configure(insertbackground="black")
        self.fr_text.configure(selectbackground="blue")
        self.fr_text.configure(selectforeground="white")
        self.fr_text.configure(wrap="word")

        self.detresse_respi = tk.Label(self.bilanrespi)
        self.detresse_respi.place(relx=0.517, rely=0.139, height=21, width=274
                , bordermode='ignore')
        self.detresse_respi.configure(activebackground="#f9f9f9")
        self.detresse_respi.configure(activeforeground="black")
        self.detresse_respi.configure(background="#d9d9d9")
        self.detresse_respi.configure(disabledforeground="#a3a3a3")
        self.detresse_respi.configure(foreground="#000000")
        self.detresse_respi.configure(highlightbackground="#d9d9d9")
        self.detresse_respi.configure(highlightcolor="black")

        self.respi_text = tk.Text(self.bilanrespi)
        self.respi_text.place(relx=0.517, rely=0.417, relheight=0.514
                , relwidth=0.457, bordermode='ignore')
        self.respi_text.configure(background="white")
        self.respi_text.configure(font=("TkTextFont", 11))
        self.respi_text.configure(foreground="black")
        self.respi_text.configure(highlightbackground="#d9d9d9")
        self.respi_text.configure(highlightcolor="black")
        self.respi_text.configure(insertbackground="black")
        self.respi_text.configure(selectbackground="blue")
        self.respi_text.configure(selectforeground="white")
        self.respi_text.configure(wrap="word")

        self.circulatoire = tk.LabelFrame(self.Frame1)
        self.circulatoire.place(relx=0.031, rely=0.38, relheight=0.227
                , relwidth=0.939)
        self.circulatoire.configure(relief='groove')
        self.circulatoire.configure(foreground="black")
        self.circulatoire.configure(text='''BILAN CIRCULATOIRE''')
        self.circulatoire.configure(background="#d9d9d9")
        self.circulatoire.configure(highlightbackground="#d9d9d9")
        self.circulatoire.configure(highlightcolor="black")

        self.fc_button = tk.Button(self.circulatoire)
        self.fc_button.place(relx=0.033, rely=0.186, height=44, width=127
                , bordermode='ignore')
        self.fc_button.configure(activebackground="#ececec")
        self.fc_button.configure(activeforeground="#000000")
        self.fc_button.configure(background="#d9d9d9")
        self.fc_button.configure(command=fc)
        self.fc_button.configure(disabledforeground="#a3a3a3")
        self.fc_button.configure(foreground="#000000")
        self.fc_button.configure(highlightbackground="#d9d9d9")
        self.fc_button.configure(highlightcolor="black")
        self.fc_button.configure(pady="0")
        self.fc_button.configure(text='''MESURE FC''')

        self.tag_button = tk.Button(self.circulatoire)
        self.tag_button.place(relx=0.267, rely=0.186, height=44, width=127
                , bordermode='ignore')
        self.tag_button.configure(activebackground="#ececec")
        self.tag_button.configure(activeforeground="#000000")
        self.tag_button.configure(background="#d9d9d9")
        self.tag_button.configure(command=tag)
        self.tag_button.configure(disabledforeground="#a3a3a3")
        self.tag_button.configure(foreground="#000000")
        self.tag_button.configure(highlightbackground="#d9d9d9")
        self.tag_button.configure(highlightcolor="black")
        self.tag_button.configure(pady="0")
        self.tag_button.configure(text='''MESURE TA Gauche''')

        self.tad_button = tk.Button(self.circulatoire)
        self.tad_button.place(relx=0.267, rely=0.605, height=44, width=127
                , bordermode='ignore')
        self.tad_button.configure(activebackground="#ececec")
        self.tad_button.configure(activeforeground="#000000")
        self.tad_button.configure(background="#d9d9d9")
        self.tad_button.configure(command=tad)
        self.tad_button.configure(disabledforeground="#a3a3a3")
        self.tad_button.configure(foreground="#000000")
        self.tad_button.configure(highlightbackground="#d9d9d9")
        self.tad_button.configure(highlightcolor="black")
        self.tad_button.configure(pady="0")
        self.tad_button.configure(text='''MESURE TA Droite''')

        self.trc_button = tk.Button(self.circulatoire)
        self.trc_button.place(relx=0.033, rely=0.605, height=44, width=127
                , bordermode='ignore')
        self.trc_button.configure(activebackground="#ececec")
        self.trc_button.configure(activeforeground="#000000")
        self.trc_button.configure(background="#d9d9d9")
        self.trc_button.configure(command=trc)
        self.trc_button.configure(disabledforeground="#a3a3a3")
        self.trc_button.configure(foreground="#000000")
        self.trc_button.configure(highlightbackground="#d9d9d9")
        self.trc_button.configure(highlightcolor="black")
        self.trc_button.configure(pady="0")
        self.trc_button.configure(text='''MESURE TRC''')

        self.detresse_circu = tk.Label(self.circulatoire)
        self.detresse_circu.place(relx=0.5, rely=0.093, height=21, width=284
                , bordermode='ignore')
        self.detresse_circu.configure(activebackground="#f9f9f9")
        self.detresse_circu.configure(activeforeground="black")
        self.detresse_circu.configure(background="#d9d9d9")
        self.detresse_circu.configure(disabledforeground="#a3a3a3")
        self.detresse_circu.configure(foreground="#000000")
        self.detresse_circu.configure(highlightbackground="#d9d9d9")
        self.detresse_circu.configure(highlightcolor="black")

        self.fc_text = tk.Text(self.circulatoire)
        self.fc_text.place(relx=0.033, rely=0.419, relheight=0.158
                , relwidth=0.212, bordermode='ignore')
        self.fc_text.configure(background="white")
        self.fc_text.configure(font=("TkTextFont", SIZE_FONT))
        self.fc_text.configure(foreground="black")
        self.fc_text.configure(highlightbackground="#d9d9d9")
        self.fc_text.configure(highlightcolor="black")
        self.fc_text.configure(insertbackground="black")
        self.fc_text.configure(selectbackground="blue")
        self.fc_text.configure(selectforeground="white")
        self.fc_text.configure(wrap="word")

        self.tag_text = tk.Text(self.circulatoire)
        self.tag_text.place(relx=0.267, rely=0.419, relheight=0.158
                , relwidth=0.212, bordermode='ignore')
        self.tag_text.configure(background="white")
        self.tag_text.configure(font=("TkTextFont", SIZE_FONT))
        self.tag_text.configure(foreground="black")
        self.tag_text.configure(highlightbackground="#d9d9d9")
        self.tag_text.configure(highlightcolor="black")
        self.tag_text.configure(insertbackground="black")
        self.tag_text.configure(selectbackground="blue")
        self.tag_text.configure(selectforeground="white")
        self.tag_text.configure(wrap="word")

        self.trc_text = tk.Text(self.circulatoire)
        self.trc_text.place(relx=0.033, rely=0.837, relheight=0.112
                , relwidth=0.212, bordermode='ignore')
        self.trc_text.configure(background="white")
        self.trc_text.configure(font=("TkTextFont", 15))
        self.trc_text.configure(foreground="black")
        self.trc_text.configure(highlightbackground="#d9d9d9")
        self.trc_text.configure(highlightcolor="black")
        self.trc_text.configure(insertbackground="black")
        self.trc_text.configure(selectbackground="blue")
        self.trc_text.configure(selectforeground="white")
        self.trc_text.configure(wrap="word")

        self.tad_text = tk.Text(self.circulatoire)
        self.tad_text.place(relx=0.267, rely=0.837, relheight=0.112
                , relwidth=0.212, bordermode='ignore')
        self.tad_text.configure(background="white")
        self.tad_text.configure(font=("TkTextFont", 15))
        self.tad_text.configure(foreground="black")
        self.tad_text.configure(highlightbackground="#d9d9d9")
        self.tad_text.configure(highlightcolor="black")
        self.tad_text.configure(insertbackground="black")
        self.tad_text.configure(selectbackground="blue")
        self.tad_text.configure(selectforeground="white")
        self.tad_text.configure(wrap="word")

        self.circu_text = tk.Text(self.circulatoire)
        self.circu_text.place(relx=0.5, rely=0.279, relheight=0.67
                , relwidth=0.473, bordermode='ignore')
        self.circu_text.configure(background="white")
        self.circu_text.configure(font=("TkTextFont", 11))
        self.circu_text.configure(foreground="black")
        self.circu_text.configure(highlightbackground="#d9d9d9")
        self.circu_text.configure(highlightcolor="black")
        self.circu_text.configure(insertbackground="black")
        self.circu_text.configure(selectbackground="blue")
        self.circu_text.configure(selectforeground="white")
        self.circu_text.configure(wrap="word")

        self.all_text = tk.Text(self.Frame1)
        self.all_text.place(relx=0.031, rely=0.623, relheight=0.359
                , relwidth=0.945)
        self.all_text.configure(background="white")
        self.all_text.configure(font=("TkTextFont", 10))
        self.all_text.configure(foreground="black")
        self.all_text.configure(highlightbackground="#d9d9d9")
        self.all_text.configure(highlightcolor="black")
        self.all_text.configure(insertbackground="black")
        self.all_text.configure(selectbackground="blue")
        self.all_text.configure(selectforeground="white")
        self.all_text.configure(wrap="word")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.015, rely=0.01, height=73, width=634)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#ff4a4a")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 24")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''PROJET EMS RP''')

if __name__ == '__main__':
    vp_start_gui()





