#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Apr 10, 2021 06:06:58 PM CEST  platform: Windows NT

import sys, random, math
from datetime import datetime
from tkinter import font
import tkinter.font as tkFont
from tkinter.constants import DISABLED, SOLID
from tkinter.scrolledtext import *
from tkinter import ttk
from tkinter import scrolledtext

# VARIABLES DE CONFIGURATION
all_index = 1.0
SIZE_FONT = 20
DELAI = 1000

# VARIABLES DE FONCTIONNEMENT
is_detresse_respi1 = 0 # respirer
is_detresse_respi2 = 0 # sat
is_detresse_respi3 = 0 # FR
is_detresse_neuro = 0 # conscience
is_detresse_circu1 = 0 # FC
is_detresse_circu2 = 0 # TAG
is_detresse_circu3 = 0 # TAD
is_detresse_circu4 = 0 # TRC

is_detresse_circu = 0
is_detresse_neuro = 0
is_detresse_respi = 0

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import projet_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    projet_support.set_Tk_var()
    top = Toplevel1 (root)
    projet_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    projet_support.set_Tk_var()
    top = Toplevel1 (w)
    projet_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):


#-----------------------------------------------------------------------------
        #MES FONCTIONS
        # getters

        def is_conscience():
                return projet_support.conscience.get()
        
        def is_respi():
                return projet_support.respire.get()

        def inter():
                return projet_support.inter.get()   
        
        def pup_taille():
                return projet_support.pup_taille.get()
        
        def pup_react():
                return projet_support.pup_react.get()

        def pup_sym():
                return projet_support.pup_sym.get()

        def espace():
                return projet_support.espace.get()

        def temps():
                return projet_support.temps.get()

        #setters

        def set_conscience(value):
                projet_support.conscience.set(value)
        
        def set_respi(value):
                projet_support.respire.set(value)

        def set_inter(value):
                projet_support.inter.set(value)   
        
        def set_pup_taille(value):
                projet_support.pup_taille.set(value)
        
        def set_pup_react(value):
                projet_support.pup_react.set(value)

        def set_pup_sym(value):
                projet_support.pup_sym.set(value)

        def set_espace(value):
                projet_support.espace.set(value)

        def set_temps(value):
                projet_support.temps.set(value)

        # detresses

        def detresse_circu():
                global is_detresse_circu
                if is_detresse_circu1 == 1 or is_detresse_circu2 == 1 or is_detresse_circu3 == 1 or is_detresse_circu4 == 1:
                        is_detresse_circu = 1
                        print("detresse circu")
                else:
                        is_detresse_circu = 0

        def detresse_respi():
                global is_detresse_respi
                if is_detresse_respi1 == 1 or is_detresse_respi2 == 1 or is_detresse_respi3 == 1:
                        is_detresse_respi = 1
                        print("detresse respi")
                else:
                        is_detresse_respi = 0

        def detresse_neuro():
                global is_detresse_neuro
                if is_detresse_neuro == 1:
                        is_detresse_neuro = 1
                        print("detresse neuro")
                else:
                        is_detresse_neuro = 0

        def blink_respi():
                if is_detresse_respi == 1:
                        if self.detresse_respi.cget("background") == "#c0c0c0":
                                self.detresse_respi.configure(background="#ff0000")     
                                self.detresse_respi.configure(highlightcolor="white")
                        else:
                                self.detresse_respi.configure(background="#c0c0c0")     
                                self.detresse_respi.configure(highlightcolor="black")
                root.after(DELAI, blink_respi)

        def blink_neuro():
                if is_detresse_neuro == 1:
                        if self.Label1.cget("background") == "#c0c0c0":
                                self.Label1.configure(background="#ff0000")     
                                self.Label1.configure(highlightcolor="white")       
                        else:
                                self.Label1.configure(background="#c0c0c0")     
                                self.Label1.configure(highlightcolor="black")
                root.after(DELAI, blink_neuro)

        def blink_circu():
                if is_detresse_circu == 1:
                        if self.detresse_circu.cget("background") == "#c0c0c0":
                                self.detresse_circu.configure(background="#ff0000")     
                                self.detresse_circu.configure(highlightcolor="white") 
                        else:
                                self.detresse_circu.configure(background="#c0c0c0")     
                                self.detresse_circu.configure(highlightcolor="black")
                root.after(DELAI, blink_circu)


        def reset_detresses():
                self.detresse_respi.configure(background="#c0c0c0")     
                self.detresse_respi.configure(highlightcolor="black")
                self.detresse_circu.configure(background="#c0c0c0")     
                self.detresse_circu.configure(highlightcolor="black")
                self.Label1.configure(background="#c0c0c0")     
                self.Label1.configure(highlightcolor="black")
                global is_detresse_respi
                global is_detresse_circu
                global is_detresse_neuro
                is_detresse_respi = 0
                is_detresse_circu = 0
                is_detresse_neuro = 0
                detresse_respi()
                detresse_circu()
                detresse_neuro()

        # FONCTION LOG

        def log(text):
                global all_index
                global is_detresse_neuro
                global is_detresse_respi1
                all_index += 1
                now = datetime.now() # current date and time
                date_time = now.strftime("%H:%M:%S > ")	
                self.log.insert(all_index, date_time + text + '\n')
                self.log.yview(all_index)
                #check state of neuro 
                if is_conscience() == 0:
                        is_detresse_neuro = 1
                else:
                        self.Label1.configure(background="#c0c0c0")     
                        self.Label1.configure(highlightcolor="black")
                        is_detresse_neuro = 0
                if is_respi() == 0:
                        is_detresse_respi1 = 1
                else:
                        is_detresse_respi1 = 0
                detresse_respi()
                detresse_neuro()
                detresse_circu() #juste au cas ou

        #TODO : tention basse comme tension haute possible en cas de detresse circu !

        def tad():
                global is_detresse_circu3
                a_list = [7,8,9,10,11,12,13,14,15,16,17,18,19]
                distribution = [0.00326 , 0.00652 , 0.0125 , 0.025 , 0.15 , 0.5 , 0.15 , 0.075 , 0.0375 , 0.0175 , 0.015 , 0.003 , 0.00146]
                if inter() == 2 or inter() == 3 or inter() == 4 or inter() == 6:
                        distribution = distribution.reverse()
                random_number = random.choices(a_list, distribution)
                random_number = int(str(random_number)[1:-1])
                random_number2 = int(((random_number/2)*10 + 10) + random.randint(0,9))
                random_number = random_number*10 + random.randint(0,9)
                if random_number >= 145:
                        self.tad_text.configure(foreground="red")
                        is_detresse_circu3 = 1
                else:
                        is_detresse_circu3 = 0
                        self.tad_text.configure(foreground="black")
                tension = str(random_number) + "/" + str(random_number2)
                tension2 = "Mesure de la tension artérielle bras droit : " + str(random_number) + "/" + str(random_number2)
                self.tad_text.delete(1.0,"end")
                self.tad_text.insert(1.0, tension)
                log(tension2)

        def tag():
                global is_detresse_circu2
                a_list = [7,8,9,10,11,12,13,14,15,16,17,18,19]
                distribution = [0.00326 , 0.00652, 0.0125 , 0.025 , 0.15 , 0.5 , 0.15 , 0.075 , 0.0375 , 0.0175 , 0.015 , 0.003 , 0.00146]
                if inter() == 2 or inter() == 3 or inter() == 4 or inter() == 6:
                        distribution = distribution.reverse()
                random_number = random.choices(a_list, distribution)
                random_number = int(str(random_number)[1:-1])
                random_number2 = int(((random_number/2)*10 + 10) + random.randint(0,9))
                random_number = random_number*10 + random.randint(0,9)
                if random_number >= 145:
                        self.tag_text.configure(foreground="red")
                        is_detresse_circu2 = 1
                else:
                        self.tag_text.configure(foreground="black")
                        is_detresse_circu2 = 0
                tension = str(random_number) + "/" + str(random_number2)
                tension2 = "Mesure de la tension artérielle bras droit : " + str(random_number) + "/" + str(random_number2)
                self.tag_text.delete(1.0,"end")
                self.tag_text.insert(1.0, tension)
                log(tension2)

       #mesure fréquence cardiaque
        def fc():
                global is_detresse_circu1
                liste = [40,50,60,80,100]
                proba = [0.05,0.15,0.15,0.5,0.15]
                if inter() == 2 or inter() == 3 or inter() == 4 or inter() == 6:
                        proba = [0.05,0.10,0.2,0.3,0.35]
                fc = random.choices(liste, proba)
                fc = int(str(fc)[1:-1])
                if fc == 40:
                        fc = random.randint(40,50)
                if fc == 50:
                        fc = random.randint(50,60)
                if fc == 60:
                        fc = random.randint(60,80)
                if fc == 80:
                        fc = random.randint(80,100)
                if fc == 100:
                        fc = random.randint(100,150)
                message = str(fc) + " bpm/min"
                self.fc_text.delete(1.0,"end")
                self.fc_text.insert(1.0, message)
                if fc >= 100:
                        self.fc_text.configure(foreground="red")
                        is_detresse_circu1 = 1
                else:
                        self.fc_text.configure(foreground="black")
                        is_detresse_circu1 = 0
                message = "Fréquence cardiaque mesurée à : " + message
                log(message)

        #TODO : frequence respi basse comme haute en detresse respi !

        #mesure fréquence respiratoire
        def fr():
                global is_detresse_respi1
                liste = [10,15,20,25,30]
                proba = [0.05,0.15,0.15,0.5,0.15]
                if is_respi() == 0:
                        is_detresse_respi1 = 1
                        fr = 0
                        self.fr_text.configure(foreground="red")
                else:
                        self.fr_text.configure(foreground="black")
                        is_detresse_respi1 = 0
                        fr = random.choices(liste, proba)
                        fr = int(str(fr)[1:-1])
                        if fr == 10:
                                fr = random.randint(0,10)
                        if fr == 15:
                                fr = random.randint(10,15)
                        if fr == 20:
                                fr = random.randint(15,20)
                        if fr == 25:
                                fr = random.randint(20,25)
                        if fr == 30:
                                fr = random.randint(25,35)
                message = str(fr) + " mv/min"
                self.fr_text.delete(1.0,"end")
                self.fr_text.insert(1.0, message)
                message = "Fréquence respiratoire mesurée à : " + message
                log(message)

        #mesure saturation pulsatile o2
        def sat():
                global is_detresse_respi2
                liste = [80,83,87,90,93,96]
                proba = [0.00625,0.00625 ,0.0125 ,0.025 , 0.05, 0.9]
                if is_respi() == 0:
                        proba = [0.05,0.9 ,0.025 ,0.0125 , 0.0625, 0.0625]                    
                sat = random.choices(liste, proba)
                sat = int(str(sat)[1:-1])
                if sat == 96:
                        sat = random.randint(96,100)
                if sat == 93:
                        sat = random.randint(93,96)
                if sat == 90:
                        sat = random.randint(90,93)
                if sat == 87:
                        sat = random.randint(87,90)
                if sat == 83:
                        sat = random.randint(83,87)
                if sat == 80:
                        sat = random.randint(80,83)
                if sat <= 94:
                        self.sat_text.configure(foreground="red")
                        is_detresse_respi2 = 1
                else:
                        self.sat_text.configure(foreground="black")
                        is_detresse_respi2 = 0
                message = str(sat) + "%"
                self.sat_text.delete(1.0,"end")
                self.sat_text.insert(1.0, message)
                message = "SAT mesurée à : " + message   
                log(message)

        # mesure trc
        def trc():
                global is_detresse_circu4
                if inter() == 2 or inter() == 3 or inter() == 4 or inter() == 6:
                        message = "TRC supérieur à 2 secondes"
                        self.trc_text.delete(1.0,"end")
                        self.trc_text.insert(1.0,">2 sec")
                        is_detresse_circu4 = 1
                        self.trc_text.configure(foreground='red')
                else:
                        is_detresse_circu4 = 0
                        message = "TRC inférieur à 2 secondes"
                        self.trc_text.delete(1.0,"end")
                        self.trc_text.insert(1.0,"<2 sec")
                        self.trc_text.configure(foreground='black')
                log(message)

        def bilan_infos():
                if inter() == 0:
                        message = "Motif d'intervention : Malaise"
                elif inter() == 1:
                        message = "Motif d'intervention : Plaie simple"
                elif inter() == 2:
                        message = "Motif d'intervention : AVP"
                elif inter() == 3:
                        message = "Motif d'intervention : Plaie par balle"
                elif inter() == 4:
                        message = "Motif d'intervention : Plaie par arme blanche"
                elif inter() == 5:
                        message = "Motif d'intervention : Autre"
                elif inter() == 6:
                        message = "Motif d'intervention : Traumatisme"
                log(message)
                if is_conscience() == 1:
                        message = "A l'arrivée des secours, victime consciente"
                else:
                        message = "A l'arrivée des secours, victime inconsciente"
                log(message)
                if is_respi() == 1:
                        message = "A l'arrivée des secours, la victime respire"
                else:
                        message = "A l'arrivée des secours, la victime ne respire pas"
                log(message)
                if espace() == 1:
                        message = "Victime orientée dans l'espace"
                else:
                        message = "Victime désorientée dans l'espace"
                log(message)
                if temps() == 1:
                        message = "Victime orientée dans le temps"
                else:
                        message = "Victime désorientée dans le temps"
                log(message)
                if pup_taille() == 1:
                        message = "Pupilles mydriase (dillatées)"
                else:
                        message = "Pupilles myosis (taille normale)"
                log(message)
                if pup_react() == 1:
                        message = "Pupilles réactives"
                else:
                        message = "Pupilles non réactives"
                log(message)
                if pup_sym() == 1:
                        message = "Pupilles symétriques"
                else:
                        message = "Pupilles non symétriques"
                log(message)

        def envoyer():
                message = ""
                identite = self.identite_entry.get()
                tel = self.tel_entry.get()
                if identite != "":
                        message = "Identité : " + identite
                        
                if tel != "":
                        message = message + " \t\t | \t\t" + "Téléphone : " + tel
                bilan_infos()
                log(message)

        def envoyer_log():
                message = self.entry_log.get()
                log(str(message))
                self.entry_log.delete(0, 'end')


        def new():
                global is_detresse_respi1
                global is_detresse_respi2
                global is_detresse_respi3
                global is_detresse_neuro
                global is_detresse_circu1
                global is_detresse_circu2
                global is_detresse_circu3
                global is_detresse_circu4
                global is_detresse_circu
                global is_detresse_neuro
                global is_detresse_respi
                message = "------------------ Nouvelle victime ------------------"
                log(message)
                self.tel_entry.delete(0,'end')
                self.identite_entry.delete(0,'end')
                self.tag_text.delete(1.0,"end")
                self.tad_text.delete(1.0,"end")
                self.fr_text.delete(1.0,"end")
                self.fc_text.delete(1.0,"end")
                self.sat_text.delete(1.0,"end")
                self.trc_text.delete(1.0,"end")
                self.entry_log.delete(0, 'end')
                reset_detresses()
                set_conscience(1)
                set_respi(1)
                set_espace(1)
                set_temps(1)
                set_inter(0)
                set_pup_react(1)
                set_pup_sym(1)
                set_pup_taille(0)
                is_detresse_respi1 = 0 # respirer
                is_detresse_respi2 = 0 # sat
                is_detresse_respi3 = 0 # FR
                is_detresse_neuro = 0 # conscience
                is_detresse_circu1 = 0 # FC
                is_detresse_circu2 = 0 # TAG
                is_detresse_circu3 = 0 # TAD
                is_detresse_circu4 = 0 # TRC
                is_detresse_circu = 0
                is_detresse_neuro = 0
                is_detresse_respi = 0

        def option1():
                a=1
        def option2():
                a=1
        def option3():
                a=1
        def option4():
                a=1
        def option5():
                a=1
        def option6():
                a=1
        def option7():
                a=1
        def option8():
                a=1
        def option9():
                a=1
        def option10():
                a=1


#------------TKINTER PAGE AUTO GENERATED BUT MODIFIED----------------------------------------------
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("621x956+766+94")
        top.minsize(120, 1)
        top.maxsize(4484, 1421)
        top.resizable(1,  1)
        top.title("Projet EMS RP - version BETA")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.titre = tk.Label(top)
        self.titre.place(relx=0.0, rely=0.0, height=31, width=624)
        self.titre.configure(activebackground="#f9f9f9")
        self.titre.configure(activeforeground="black")
        self.titre.configure(background="#fd0006")
        self.titre.configure(disabledforeground="#a3a3a3")
        self.titre.configure(font="-family {Segoe UI} -size 18 -weight bold")
        self.titre.configure(foreground="#ffffff")
        self.titre.configure(highlightbackground="#d9d9d9")
        self.titre.configure(highlightcolor="black")
        self.titre.configure(text='''PROJET EMS RP''')

        self.informations = tk.LabelFrame(top)
        self.informations.place(relx=0.016, rely=0.042, relheight=0.052
                , relwidth=0.968)
        self.informations.configure(relief='groove')
        self.informations.configure(foreground="black")
        self.informations.configure(text='''INFORMATIONS''')
        self.informations.configure(background="#d9d9d9")
        self.informations.configure(highlightbackground="#d9d9d9")
        self.informations.configure(highlightcolor="black")

        self.nouvelle_victime = tk.Button(self.informations)
        self.nouvelle_victime.place(relx=0.017, rely=0.42, height=24, width=107
                , bordermode='ignore')
        self.nouvelle_victime.configure(activebackground="#ececec")
        self.nouvelle_victime.configure(activeforeground="#000000")
        self.nouvelle_victime.configure(background="#d9d9d9")
        self.nouvelle_victime.configure(command=new)
        self.nouvelle_victime.configure(disabledforeground="#a3a3a3")
        self.nouvelle_victime.configure(foreground="#000000")
        self.nouvelle_victime.configure(highlightbackground="#d9d9d9")
        self.nouvelle_victime.configure(highlightcolor="black")
        self.nouvelle_victime.configure(pady="0")
        self.nouvelle_victime.configure(text='''Nouvelle victime''')

        self.identite_entry = tk.Entry(self.informations)
        self.identite_entry.place(relx=0.316, rely=0.4, height=20, relwidth=0.223
                , bordermode='ignore')
        self.identite_entry.configure(background="white")
        self.identite_entry.configure(disabledforeground="#a3a3a3")
        self.identite_entry.configure(font=("TkTextFont", 14))
        self.identite_entry.configure(foreground="#000000")
        self.identite_entry.configure(highlightbackground="#d9d9d9")
        self.identite_entry.configure(highlightcolor="black")
        self.identite_entry.configure(insertbackground="black")
        self.identite_entry.configure(selectbackground="blue")
        self.identite_entry.configure(selectforeground="white")

        self.identite = tk.Label(self.informations)
        self.identite.place(relx=0.216, rely=0.4, height=15, width=54
                , bordermode='ignore')
        self.identite.configure(activebackground="#f9f9f9")
        self.identite.configure(activeforeground="black")
        self.identite.configure(background="#d9d9d9")
        self.identite.configure(disabledforeground="#a3a3a3")
        self.identite.configure(foreground="#000000")
        self.identite.configure(highlightbackground="#d9d9d9")
        self.identite.configure(highlightcolor="black")
        self.identite.configure(text='''Identité :''')

        self.tel = tk.Label(self.informations)
        self.tel.place(relx=0.566, rely=0.4, height=15, width=74
                , bordermode='ignore')
        self.tel.configure(activebackground="#f9f9f9")
        self.tel.configure(activeforeground="black")
        self.tel.configure(background="#d9d9d9")
        self.tel.configure(disabledforeground="#a3a3a3")
        self.tel.configure(foreground="#000000")
        self.tel.configure(highlightbackground="#d9d9d9")
        self.tel.configure(highlightcolor="black")
        self.tel.configure(text='''N° téléphone :''')

        self.tel_entry = tk.Entry(self.informations)
        self.tel_entry.place(relx=0.699, rely=0.4, height=20, relwidth=0.19
                , bordermode='ignore')
        self.tel_entry.configure(background="white")
        self.tel_entry.configure(disabledforeground="#a3a3a3")
        self.tel_entry.configure(font=("TkTextFont", 14))
        self.tel_entry.configure(foreground="#000000")
        self.tel_entry.configure(highlightbackground="#d9d9d9")
        self.tel_entry.configure(highlightcolor="black")
        self.tel_entry.configure(insertbackground="black")
        self.tel_entry.configure(selectbackground="blue")
        self.tel_entry.configure(selectforeground="white")

        self.new_ok_button = tk.Button(self.informations)
        self.new_ok_button.place(relx=0.899, rely=0.4, height=24, width=47
                , bordermode='ignore')
        self.new_ok_button.configure(activebackground="#ececec")
        self.new_ok_button.configure(activeforeground="#000000")
        self.new_ok_button.configure(background="#d9d9d9")
        self.new_ok_button.configure(command=envoyer)
        self.new_ok_button.configure(disabledforeground="#a3a3a3")
        self.new_ok_button.configure(foreground="#000000")
        self.new_ok_button.configure(highlightbackground="#d9d9d9")
        self.new_ok_button.configure(highlightcolor="black")
        self.new_ok_button.configure(pady="0")
        self.new_ok_button.configure(text='''OK''')

        self.conscience = tk.LabelFrame(top)
        self.conscience.place(relx=0.016, rely=0.188, relheight=0.062
                , relwidth=0.501)
        self.conscience.configure(relief='groove')
        self.conscience.configure(foreground="black")
        self.conscience.configure(text='''CONSCIENCE''')
        self.conscience.configure(background="#d9d9d9")
        self.conscience.configure(highlightbackground="#d9d9d9")
        self.conscience.configure(highlightcolor="black")

        self.conscience_oui = tk.Radiobutton(self.conscience)
        self.conscience_oui.place(relx=0.418, rely=0.339, relheight=0.407
                , relwidth=0.186, bordermode='ignore')
        self.conscience_oui.configure(activebackground="#ececec")
        self.conscience_oui.configure(activeforeground="#000000")
        self.conscience_oui.configure(background="#d9d9d9")
        self.conscience_oui.configure(disabledforeground="#a3a3a3")
        self.conscience_oui.configure(foreground="#000000")
        self.conscience_oui.configure(highlightbackground="#d9d9d9")
        self.conscience_oui.configure(highlightcolor="black")
        self.conscience_oui.configure(justify='left')
        self.conscience_oui.configure(text='''OUI''')
        self.conscience_oui.configure(value="1")
        self.conscience_oui.configure(variable=projet_support.conscience)

        self.conscience_non = tk.Radiobutton(self.conscience)
        self.conscience_non.place(relx=0.643, rely=0.339, relheight=0.407
                , relwidth=0.186, bordermode='ignore')
        self.conscience_non.configure(activebackground="#ececec")
        self.conscience_non.configure(activeforeground="#000000")
        self.conscience_non.configure(background="#d9d9d9")
        self.conscience_non.configure(disabledforeground="#a3a3a3")
        self.conscience_non.configure(foreground="#000000")
        self.conscience_non.configure(highlightbackground="#d9d9d9")
        self.conscience_non.configure(highlightcolor="black")
        self.conscience_non.configure(justify='left')
        self.conscience_non.configure(text='''NON''')
        self.conscience_non.configure(value="0")
        self.conscience_non.configure(variable=projet_support.conscience)

        self.respire = tk.LabelFrame(top)
        self.respire.place(relx=0.531, rely=0.188, relheight=0.062
                , relwidth=0.451)
        self.respire.configure(relief='groove')
        self.respire.configure(foreground="black")
        self.respire.configure(text='''RESPIRE''')
        self.respire.configure(background="#d9d9d9")
        self.respire.configure(highlightbackground="#d9d9d9")
        self.respire.configure(highlightcolor="black")

        self.respire_oui = tk.Radiobutton(self.respire)
        self.respire_oui.place(relx=0.393, rely=0.322, relheight=0.407
                , relwidth=0.207, bordermode='ignore')
        self.respire_oui.configure(activebackground="#ececec")
        self.respire_oui.configure(activeforeground="#000000")
        self.respire_oui.configure(background="#d9d9d9")
        self.respire_oui.configure(disabledforeground="#a3a3a3")
        self.respire_oui.configure(foreground="#000000")
        self.respire_oui.configure(highlightbackground="#d9d9d9")
        self.respire_oui.configure(highlightcolor="black")
        self.respire_oui.configure(justify='left')
        self.respire_oui.configure(text='''OUI''')
        self.respire_oui.configure(value="1")
        self.respire_oui.configure(variable=projet_support.respire)

        self.resspire_non = tk.Radiobutton(self.respire)
        self.resspire_non.place(relx=0.643, rely=0.322, relheight=0.407
                , relwidth=0.207, bordermode='ignore')
        self.resspire_non.configure(activebackground="#ececec")
        self.resspire_non.configure(activeforeground="#000000")
        self.resspire_non.configure(background="#d9d9d9")
        self.resspire_non.configure(disabledforeground="#a3a3a3")
        self.resspire_non.configure(foreground="#000000")
        self.resspire_non.configure(highlightbackground="#d9d9d9")
        self.resspire_non.configure(highlightcolor="black")
        self.resspire_non.configure(justify='left')
        self.resspire_non.configure(text='''NON''')
        self.resspire_non.configure(value="0")
        self.resspire_non.configure(variable=projet_support.respire)

        self.respiratoire = tk.LabelFrame(top)
        self.respiratoire.place(relx=0.016, rely=0.262, relheight=0.159
                , relwidth=0.966)
        self.respiratoire.configure(relief='groove')
        self.respiratoire.configure(foreground="black")
        self.respiratoire.configure(text='''BILAN RESPIRATOIRE''')
        self.respiratoire.configure(background="#d9d9d9")
        self.respiratoire.configure(highlightbackground="#d9d9d9")
        self.respiratoire.configure(highlightcolor="black")

        self.sat_button = tk.Button(self.respiratoire)
        self.sat_button.place(relx=0.05, rely=0.204, height=44, width=107
                , bordermode='ignore')
        self.sat_button.configure(activebackground="#ececec")
        self.sat_button.configure(activeforeground="#000000")
        self.sat_button.configure(background="#d9d9d9")
        self.sat_button.configure(command=sat)
        self.sat_button.configure(disabledforeground="#a3a3a3")
        self.sat_button.configure(foreground="#000000")
        self.sat_button.configure(highlightbackground="#d9d9d9")
        self.sat_button.configure(highlightcolor="black")
        self.sat_button.configure(pady="0")
        self.sat_button.configure(text='''Mesurer la SAT''')

        self.sat_text = tk.Text(self.respiratoire)
        self.sat_text.place(relx=0.05, rely=0.546, relheight=0.237
                , relwidth=0.178, bordermode='ignore')
        self.sat_text.configure(background="white")
        self.sat_text.configure(font=("TkTextFont", 16))
        self.sat_text.configure(foreground="black")
        self.sat_text.configure(highlightbackground="#d9d9d9")
        self.sat_text.configure(highlightcolor="black")
        self.sat_text.configure(insertbackground="black")
        self.sat_text.configure(selectbackground="blue")
        self.sat_text.configure(selectforeground="white")
        self.sat_text.configure(wrap="word")

        self.respi_button = tk.Button(self.respiratoire)
        self.respi_button.place(relx=0.267, rely=0.204, height=44, width=107
                , bordermode='ignore')
        self.respi_button.configure(activebackground="#ececec")
        self.respi_button.configure(activeforeground="#000000")
        self.respi_button.configure(background="#d9d9d9")
        self.respi_button.configure(command=fr)
        self.respi_button.configure(disabledforeground="#a3a3a3")
        self.respi_button.configure(foreground="#000000")
        self.respi_button.configure(highlightbackground="#d9d9d9")
        self.respi_button.configure(highlightcolor="black")
        self.respi_button.configure(pady="0")
        self.respi_button.configure(text='''Mesurer la FR''')

        self.fr_text = tk.Text(self.respiratoire)
        self.fr_text.place(relx=0.267, rely=0.546, relheight=0.237
                , relwidth=0.178, bordermode='ignore')
        self.fr_text.configure(background="white")
        self.fr_text.configure(font=("TkTextFont", 14))
        self.fr_text.configure(foreground="black")
        self.fr_text.configure(highlightbackground="#d9d9d9")
        self.fr_text.configure(highlightcolor="black")
        self.fr_text.configure(insertbackground="black")
        self.fr_text.configure(selectbackground="blue")
        self.fr_text.configure(selectforeground="white")
        self.fr_text.configure(wrap="word")

        self.TSeparator1 = ttk.Separator(self.respiratoire)
        self.TSeparator1.place(relx=0.52, rely=0.072, relheight=1.145
                , bordermode='ignore')
        self.TSeparator1.configure(orient="vertical")

        self.detresse_respi = tk.Label(self.respiratoire)
        self.detresse_respi.place(relx=0.55, rely=0.132, height=31, width=254
                , bordermode='ignore')
        self.detresse_respi.configure(activebackground="#f9f9f9")
        self.detresse_respi.configure(activeforeground="black")
        self.detresse_respi.configure(background="#c0c0c0")
        self.detresse_respi.configure(disabledforeground="#a3a3a3")
        self.detresse_respi.configure(font="-family {Segoe UI} -size 12 -weight bold")
        self.detresse_respi.configure(foreground="#000000")
        self.detresse_respi.configure(highlightbackground="#d9d9d9")
        self.detresse_respi.configure(highlightcolor="black")
        self.detresse_respi.configure(text='''DETRESSE RESPIRATOIRE''')

        self.detresse_circu = tk.Label(self.respiratoire)
        self.detresse_circu.place(relx=0.55, rely=0.395, height=31, width=254
                , bordermode='ignore')
        self.detresse_circu.configure(activebackground="#f9f9f9")
        self.detresse_circu.configure(activeforeground="black")
        self.detresse_circu.configure(background="#c0c0c0")
        self.detresse_circu.configure(disabledforeground="#a3a3a3")
        self.detresse_circu.configure(font="-family {Segoe UI} -size 12 -weight bold")
        self.detresse_circu.configure(foreground="#000000")
        self.detresse_circu.configure(highlightbackground="#d9d9d9")
        self.detresse_circu.configure(highlightcolor="black")
        self.detresse_circu.configure(text='''DETRESSE CIRCULATOIRE''')

        self.Label1 = tk.Label(self.respiratoire)
        self.Label1.place(relx=0.55, rely=0.658, height=31, width=254
                , bordermode='ignore')
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#c0c0c0")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 12 -weight bold")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''DETRESSE NEUROLOGIQUE''')

        self.circulatoire = tk.LabelFrame(top)
        self.circulatoire.place(relx=0.016, rely=0.429, relheight=0.18
                , relwidth=0.501)
        self.circulatoire.configure(relief='groove')
        self.circulatoire.configure(foreground="black")
        self.circulatoire.configure(text='''BILAN CIRCULATOIRE''')
        self.circulatoire.configure(background="#d9d9d9")
        self.circulatoire.configure(highlightbackground="#d9d9d9")
        self.circulatoire.configure(highlightcolor="black")

        self.tag = tk.Button(self.circulatoire)
        self.tag.place(relx=0.064, rely=0.174, height=34, width=137
                , bordermode='ignore')
        self.tag.configure(activebackground="#ececec")
        self.tag.configure(activeforeground="#000000")
        self.tag.configure(background="#d9d9d9")
        self.tag.configure(command=tag)
        self.tag.configure(disabledforeground="#a3a3a3")
        self.tag.configure(foreground="#000000")
        self.tag.configure(highlightbackground="#d9d9d9")
        self.tag.configure(highlightcolor="black")
        self.tag.configure(pady="0")
        self.tag.configure(text='''Mesurer TA Gauche''')

        self.tad = tk.Button(self.circulatoire)
        self.tad.place(relx=0.547, rely=0.174, height=34, width=127
                , bordermode='ignore')
        self.tad.configure(activebackground="#ececec")
        self.tad.configure(activeforeground="#000000")
        self.tad.configure(background="#d9d9d9")
        self.tad.configure(command=tad)
        self.tad.configure(disabledforeground="#a3a3a3")
        self.tad.configure(foreground="#000000")
        self.tad.configure(highlightbackground="#d9d9d9")
        self.tad.configure(highlightcolor="black")
        self.tad.configure(pady="0")
        self.tad.configure(text='''Mesurer TA Droite''')

        self.tag_text = tk.Text(self.circulatoire)
        self.tag_text.place(relx=0.064, rely=0.407, relheight=0.14
                , relwidth=0.441, bordermode='ignore')
        self.tag_text.configure(background="white")
        self.tag_text.configure(font=("TkTextFont", 14))
        self.tag_text.configure(foreground="black")
        self.tag_text.configure(highlightbackground="#d9d9d9")
        self.tag_text.configure(highlightcolor="black")
        self.tag_text.configure(insertbackground="black")
        self.tag_text.configure(selectbackground="blue")
        self.tag_text.configure(selectforeground="white")
        self.tag_text.configure(wrap="word")

        self.fc = tk.Button(self.circulatoire)
        self.fc.place(relx=0.064, rely=0.587, height=34, width=137
                , bordermode='ignore')
        self.fc.configure(activebackground="#ececec")
        self.fc.configure(activeforeground="#000000")
        self.fc.configure(background="#d9d9d9")
        self.fc.configure(command=fc)
        self.fc.configure(disabledforeground="#a3a3a3")
        self.fc.configure(foreground="#000000")
        self.fc.configure(highlightbackground="#d9d9d9")
        self.fc.configure(highlightcolor="black")
        self.fc.configure(pady="0")
        self.fc.configure(text='''Mesurer FC''')

        self.tad_text = tk.Text(self.circulatoire)
        self.tad_text.place(relx=0.547, rely=0.407, relheight=0.14
                , relwidth=0.408, bordermode='ignore')
        self.tad_text.configure(background="white")
        self.tad_text.configure(font=("TkTextFont", 14))
        self.tad_text.configure(foreground="black")
        self.tad_text.configure(highlightbackground="#d9d9d9")
        self.tad_text.configure(highlightcolor="black")
        self.tad_text.configure(insertbackground="black")
        self.tad_text.configure(selectbackground="blue")
        self.tad_text.configure(selectforeground="white")
        self.tad_text.configure(wrap="word")

        self.trc_button = tk.Button(self.circulatoire)
        self.trc_button.place(relx=0.547, rely=0.581, height=34, width=127
                , bordermode='ignore')
        self.trc_button.configure(activebackground="#ececec")
        self.trc_button.configure(activeforeground="#000000")
        self.trc_button.configure(background="#d9d9d9")
        self.trc_button.configure(command=trc)
        self.trc_button.configure(disabledforeground="#a3a3a3")
        self.trc_button.configure(foreground="#000000")
        self.trc_button.configure(highlightbackground="#d9d9d9")
        self.trc_button.configure(highlightcolor="black")
        self.trc_button.configure(pady="0")
        self.trc_button.configure(text='''Mesurer TRC''')

        self.fc_text = tk.Text(self.circulatoire)
        self.fc_text.place(relx=0.064, rely=0.814, relheight=0.14, relwidth=0.441
                , bordermode='ignore')
        self.fc_text.configure(background="white")
        self.fc_text.configure(font=("TkTextFont", 14))
        self.fc_text.configure(foreground="black")
        self.fc_text.configure(highlightbackground="#d9d9d9")
        self.fc_text.configure(highlightcolor="black")
        self.fc_text.configure(insertbackground="black")
        self.fc_text.configure(selectbackground="blue")
        self.fc_text.configure(selectforeground="white")
        self.fc_text.configure(wrap="word")

        self.trc_text = tk.Text(self.circulatoire)
        self.trc_text.place(relx=0.547, rely=0.814, relheight=0.14
                , relwidth=0.408, bordermode='ignore')
        self.trc_text.configure(background="white")
        self.trc_text.configure(font=("TkTextFont", 14))
        self.trc_text.configure(foreground="black")
        self.trc_text.configure(highlightbackground="#d9d9d9")
        self.trc_text.configure(highlightcolor="black")
        self.trc_text.configure(insertbackground="black")
        self.trc_text.configure(selectbackground="blue")
        self.trc_text.configure(selectforeground="white")
        self.trc_text.configure(wrap="word")

        self.neuro = tk.LabelFrame(top)
        self.neuro.place(relx=0.531, rely=0.429, relheight=0.253, relwidth=0.451)
        self.neuro.configure(relief='groove')
        self.neuro.configure(foreground="black")
        self.neuro.configure(text='''BILAN NEUROLOGIQUE''')
        self.neuro.configure(background="#d9d9d9")
        self.neuro.configure(highlightbackground="#d9d9d9")
        self.neuro.configure(highlightcolor="black")

        self.pupilles = tk.LabelFrame(self.neuro)
        self.pupilles.place(relx=0.036, rely=0.083, relheight=0.488
                , relwidth=0.929, bordermode='ignore')
        self.pupilles.configure(relief='groove')
        self.pupilles.configure(foreground="black")
        self.pupilles.configure(text='''Pupilles''')
        self.pupilles.configure(background="#d9d9d9")
        self.pupilles.configure(highlightbackground="#d9d9d9")
        self.pupilles.configure(highlightcolor="black")

        self.pup1 = tk.Radiobutton(self.pupilles)
        self.pup1.place(relx=0.231, rely=0.144, relheight=0.178, relwidth=0.262
                , bordermode='ignore')
        self.pup1.configure(activebackground="#ececec")
        self.pup1.configure(activeforeground="#000000")
        self.pup1.configure(background="#d9d9d9")
        self.pup1.configure(disabledforeground="#a3a3a3")
        self.pup1.configure(foreground="#000000")
        self.pup1.configure(highlightbackground="#d9d9d9")
        self.pup1.configure(highlightcolor="black")
        self.pup1.configure(justify='left')
        self.pup1.configure(text='''Myosis''')
        self.pup1.configure(value="0")
        self.pup1.configure(variable=projet_support.pup_taille)

        self.pup12 = tk.Radiobutton(self.pupilles)
        self.pup12.place(relx=0.577, rely=0.144, relheight=0.178, relwidth=0.338
                , bordermode='ignore')
        self.pup12.configure(activebackground="#ececec")
        self.pup12.configure(activeforeground="#000000")
        self.pup12.configure(background="#d9d9d9")
        self.pup12.configure(disabledforeground="#a3a3a3")
        self.pup12.configure(foreground="#000000")
        self.pup12.configure(highlightbackground="#d9d9d9")
        self.pup12.configure(highlightcolor="black")
        self.pup12.configure(justify='left')
        self.pup12.configure(text='''Mydriase''')
        self.pup12.configure(value="1")
        self.pup12.configure(variable=projet_support.pup_taille)

        self.pup2 = tk.Radiobutton(self.pupilles)
        self.pup2.place(relx=0.231, rely=0.364, relheight=0.178, relwidth=0.3
                , bordermode='ignore')
        self.pup2.configure(activebackground="#ececec")
        self.pup2.configure(activeforeground="#000000")
        self.pup2.configure(background="#d9d9d9")
        self.pup2.configure(disabledforeground="#a3a3a3")
        self.pup2.configure(foreground="#000000")
        self.pup2.configure(highlightbackground="#d9d9d9")
        self.pup2.configure(highlightcolor="black")
        self.pup2.configure(justify='left')
        self.pup2.configure(text='''Réactives''')
        self.pup2.configure(value="1")
        self.pup2.configure(variable=projet_support.pup_react)

        self.pup22 = tk.Radiobutton(self.pupilles)
        self.pup22.place(relx=0.577, rely=0.364, relheight=0.178, relwidth=0.338
                , bordermode='ignore')
        self.pup22.configure(activebackground="#ececec")
        self.pup22.configure(activeforeground="#000000")
        self.pup22.configure(background="#d9d9d9")
        self.pup22.configure(disabledforeground="#a3a3a3")
        self.pup22.configure(foreground="#000000")
        self.pup22.configure(highlightbackground="#d9d9d9")
        self.pup22.configure(highlightcolor="black")
        self.pup22.configure(justify='left')
        self.pup22.configure(text='''Aréactives''')
        self.pup22.configure(value="0")
        self.pup22.configure(variable=projet_support.pup_react)

        self.pup3 = tk.Radiobutton(self.pupilles)
        self.pup3.place(relx=0.192, rely=0.576, relheight=0.186, relwidth=0.338
                , bordermode='ignore')
        self.pup3.configure(activebackground="#ececec")
        self.pup3.configure(activeforeground="#000000")
        self.pup3.configure(background="#d9d9d9")
        self.pup3.configure(disabledforeground="#a3a3a3")
        self.pup3.configure(foreground="#000000")
        self.pup3.configure(highlightbackground="#d9d9d9")
        self.pup3.configure(highlightcolor="black")
        self.pup3.configure(justify='left')
        self.pup3.configure(text='''Symétriques''')
        self.pup3.configure(value="1")
        self.pup3.configure(variable=projet_support.pup_sym)

        self.pup32 = tk.Radiobutton(self.pupilles)
        self.pup32.place(relx=0.615, rely=0.576, relheight=0.186, relwidth=0.338
                , bordermode='ignore')
        self.pup32.configure(activebackground="#ececec")
        self.pup32.configure(activeforeground="#000000")
        self.pup32.configure(background="#d9d9d9")
        self.pup32.configure(disabledforeground="#a3a3a3")
        self.pup32.configure(foreground="#000000")
        self.pup32.configure(highlightbackground="#d9d9d9")
        self.pup32.configure(highlightcolor="black")
        self.pup32.configure(justify='left')
        self.pup32.configure(text='''Asymétriques''')
        self.pup32.configure(value="0")
        self.pup32.configure(variable=projet_support.pup_sym)

        self.oorientation = tk.LabelFrame(self.neuro)
        self.oorientation.place(relx=0.036, rely=0.579, relheight=0.393
                , relwidth=0.929, bordermode='ignore')
        self.oorientation.configure(relief='groove')
        self.oorientation.configure(foreground="black")
        self.oorientation.configure(text='''Orientation''')
        self.oorientation.configure(background="#d9d9d9")
        self.oorientation.configure(highlightbackground="#d9d9d9")
        self.oorientation.configure(highlightcolor="black")

        self.espace = tk.Label(self.oorientation)
        self.espace.place(relx=0.077, rely=0.316, height=21, width=54
                , bordermode='ignore')
        self.espace.configure(activebackground="#f9f9f9")
        self.espace.configure(activeforeground="black")
        self.espace.configure(background="#d9d9d9")
        self.espace.configure(disabledforeground="#a3a3a3")
        self.espace.configure(foreground="#000000")
        self.espace.configure(highlightbackground="#d9d9d9")
        self.espace.configure(highlightcolor="black")
        self.espace.configure(text='''Espace''')

        self.temps = tk.Label(self.oorientation)
        self.temps.place(relx=0.077, rely=0.632, height=21, width=54
                , bordermode='ignore')
        self.temps.configure(activebackground="#f9f9f9")
        self.temps.configure(activeforeground="black")
        self.temps.configure(background="#d9d9d9")
        self.temps.configure(disabledforeground="#a3a3a3")
        self.temps.configure(foreground="#000000")
        self.temps.configure(highlightbackground="#d9d9d9")
        self.temps.configure(highlightcolor="black")
        self.temps.configure(text='''Temps''')

        self.espace_oui = tk.Radiobutton(self.oorientation)
        self.espace_oui.place(relx=0.385, rely=0.316, relheight=0.263
                , relwidth=0.223, bordermode='ignore')
        self.espace_oui.configure(activebackground="#ececec")
        self.espace_oui.configure(activeforeground="#000000")
        self.espace_oui.configure(background="#d9d9d9")
        self.espace_oui.configure(disabledforeground="#a3a3a3")
        self.espace_oui.configure(foreground="#000000")
        self.espace_oui.configure(highlightbackground="#d9d9d9")
        self.espace_oui.configure(highlightcolor="black")
        self.espace_oui.configure(justify='left')
        self.espace_oui.configure(text='''OUI''')
        self.espace_oui.configure(value="1")
        self.espace_oui.configure(variable=projet_support.espace)

        self.espace_non = tk.Radiobutton(self.oorientation)
        self.espace_non.place(relx=0.654, rely=0.316, relheight=0.263
                , relwidth=0.223, bordermode='ignore')
        self.espace_non.configure(activebackground="#ececec")
        self.espace_non.configure(activeforeground="#000000")
        self.espace_non.configure(background="#d9d9d9")
        self.espace_non.configure(disabledforeground="#a3a3a3")
        self.espace_non.configure(foreground="#000000")
        self.espace_non.configure(highlightbackground="#d9d9d9")
        self.espace_non.configure(highlightcolor="black")
        self.espace_non.configure(justify='left')
        self.espace_non.configure(text='''NON''')
        self.espace_non.configure(value="0")
        self.espace_non.configure(variable=projet_support.espace)

        self.temps_oui = tk.Radiobutton(self.oorientation)
        self.temps_oui.place(relx=0.385, rely=0.632, relheight=0.263
                , relwidth=0.223, bordermode='ignore')
        self.temps_oui.configure(activebackground="#ececec")
        self.temps_oui.configure(activeforeground="#000000")
        self.temps_oui.configure(background="#d9d9d9")
        self.temps_oui.configure(disabledforeground="#a3a3a3")
        self.temps_oui.configure(foreground="#000000")
        self.temps_oui.configure(highlightbackground="#d9d9d9")
        self.temps_oui.configure(highlightcolor="black")
        self.temps_oui.configure(justify='left')
        self.temps_oui.configure(text='''OUI''')
        self.temps_oui.configure(value="1")
        self.temps_oui.configure(variable=projet_support.temps)

        self.temps_non = tk.Radiobutton(self.oorientation)
        self.temps_non.place(relx=0.654, rely=0.632, relheight=0.263
                , relwidth=0.223, bordermode='ignore')
        self.temps_non.configure(activebackground="#ececec")
        self.temps_non.configure(activeforeground="#000000")
        self.temps_non.configure(background="#d9d9d9")
        self.temps_non.configure(disabledforeground="#a3a3a3")
        self.temps_non.configure(foreground="#000000")
        self.temps_non.configure(highlightbackground="#d9d9d9")
        self.temps_non.configure(highlightcolor="black")
        self.temps_non.configure(justify='left')
        self.temps_non.configure(text='''NON''')
        self.temps_non.configure(value="0")
        self.temps_non.configure(variable=projet_support.temps)

        self.intervention = tk.LabelFrame(top)
        self.intervention.place(relx=0.016, rely=0.105, relheight=0.076
                , relwidth=0.966)
        self.intervention.configure(relief='groove')
        self.intervention.configure(foreground="black")
        self.intervention.configure(text='''INTERVENTION''')
        self.intervention.configure(background="#d9d9d9")
        self.intervention.configure(highlightbackground="#d9d9d9")
        self.intervention.configure(highlightcolor="black")

        self.inter_0 = tk.Radiobutton(self.intervention)
        self.inter_0.place(relx=0.017, rely=0.411, relheight=0.342
                , relwidth=0.097, bordermode='ignore')
        self.inter_0.configure(activebackground="#ececec")
        self.inter_0.configure(activeforeground="#000000")
        self.inter_0.configure(background="#d9d9d9")
        self.inter_0.configure(disabledforeground="#a3a3a3")
        self.inter_0.configure(foreground="#000000")
        self.inter_0.configure(highlightbackground="#d9d9d9")
        self.inter_0.configure(highlightcolor="black")
        self.inter_0.configure(justify='left')
        self.inter_0.configure(text='''Malaise''')
        self.inter_0.configure(value="0")
        self.inter_0.configure(variable=projet_support.inter)

        self.inter_1 = tk.Radiobutton(self.intervention)
        self.inter_1.place(relx=0.133, rely=0.411, relheight=0.342
                , relwidth=0.147, bordermode='ignore')
        self.inter_1.configure(activebackground="#ececec")
        self.inter_1.configure(activeforeground="#000000")
        self.inter_1.configure(background="#d9d9d9")
        self.inter_1.configure(disabledforeground="#a3a3a3")
        self.inter_1.configure(foreground="#000000")
        self.inter_1.configure(highlightbackground="#d9d9d9")
        self.inter_1.configure(highlightcolor="black")
        self.inter_1.configure(justify='left')
        self.inter_1.configure(text='''Plaie simple''')
        self.inter_1.configure(value="1")
        self.inter_1.configure(variable=projet_support.inter)

        self.inter_2 = tk.Radiobutton(self.intervention)
        self.inter_2.place(relx=0.283, rely=0.411, relheight=0.342
                , relwidth=0.113, bordermode='ignore')
        self.inter_2.configure(activebackground="#ececec")
        self.inter_2.configure(activeforeground="#000000")
        self.inter_2.configure(background="#d9d9d9")
        self.inter_2.configure(disabledforeground="#a3a3a3")
        self.inter_2.configure(foreground="#000000")
        self.inter_2.configure(highlightbackground="#d9d9d9")
        self.inter_2.configure(highlightcolor="black")
        self.inter_2.configure(justify='left')
        self.inter_2.configure(text='''AVP''')
        self.inter_2.configure(value="2")
        self.inter_2.configure(variable=projet_support.inter)

        self.inter_3 = tk.Radiobutton(self.intervention)
        self.inter_3.place(relx=0.417, rely=0.137, relheight=0.342
                , relwidth=0.163, bordermode='ignore')
        self.inter_3.configure(activebackground="#ececec")
        self.inter_3.configure(activeforeground="#000000")
        self.inter_3.configure(background="#d9d9d9")
        self.inter_3.configure(disabledforeground="#a3a3a3")
        self.inter_3.configure(foreground="#000000")
        self.inter_3.configure(highlightbackground="#d9d9d9")
        self.inter_3.configure(highlightcolor="black")
        self.inter_3.configure(justify='left')
        self.inter_3.configure(text='''Plaie par balle''')
        self.inter_3.configure(value="3")
        self.inter_3.configure(variable=projet_support.inter)

        self.inter_4 = tk.Radiobutton(self.intervention)
        self.inter_4.place(relx=0.417, rely=0.548, relheight=0.342, relwidth=0.23
                , bordermode='ignore')
        self.inter_4.configure(activebackground="#ececec")
        self.inter_4.configure(activeforeground="#000000")
        self.inter_4.configure(background="#d9d9d9")
        self.inter_4.configure(disabledforeground="#a3a3a3")
        self.inter_4.configure(foreground="#000000")
        self.inter_4.configure(highlightbackground="#d9d9d9")
        self.inter_4.configure(highlightcolor="black")
        self.inter_4.configure(justify='left')
        self.inter_4.configure(text='''Plaie par arme blanche''')
        self.inter_4.configure(value="4")
        self.inter_4.configure(variable=projet_support.inter)

        self.inter_5 = tk.Radiobutton(self.intervention)
        self.inter_5.place(relx=0.833, rely=0.411, relheight=0.342
                , relwidth=0.147, bordermode='ignore')
        self.inter_5.configure(activebackground="#ececec")
        self.inter_5.configure(activeforeground="#000000")
        self.inter_5.configure(background="#d9d9d9")
        self.inter_5.configure(disabledforeground="#a3a3a3")
        self.inter_5.configure(foreground="#000000")
        self.inter_5.configure(highlightbackground="#d9d9d9")
        self.inter_5.configure(highlightcolor="black")
        self.inter_5.configure(justify='left')
        self.inter_5.configure(text='''Autre''')
        self.inter_5.configure(value="5")
        self.inter_5.configure(variable=projet_support.inter)

        self.inter_6 = tk.Radiobutton(self.intervention)
        self.inter_6.place(relx=0.683, rely=0.411, relheight=0.342
                , relwidth=0.147, bordermode='ignore')
        self.inter_6.configure(activebackground="#ececec")
        self.inter_6.configure(activeforeground="#000000")
        self.inter_6.configure(background="#d9d9d9")
        self.inter_6.configure(disabledforeground="#a3a3a3")
        self.inter_6.configure(foreground="#000000")
        self.inter_6.configure(highlightbackground="#d9d9d9")
        self.inter_6.configure(highlightcolor="black")
        self.inter_6.configure(justify='left')
        self.inter_6.configure(text='''Traumatisme''')
        self.inter_6.configure(value="6")
        self.inter_6.configure(variable=projet_support.inter)

        self.log = scrolledtext.ScrolledText(top)
        self.log.place(relx=0.016, rely=0.69, relheight=0.266, relwidth=0.966)
        self.log.configure(background="white")
        self.log.configure(font="TkTextFont")
        self.log.configure(foreground="black")
        self.log.configure(highlightbackground="#d9d9d9")
        self.log.configure(highlightcolor="black")
        self.log.configure(insertbackground="black")
        self.log.configure(selectbackground="blue")
        self.log.configure(selectforeground="white")
        self.log.configure(wrap="word")

        self.entry_log = tk.Entry(top)
        self.entry_log.place(relx=0.097, rely=0.962, height=20, relwidth=0.747)
        self.entry_log.configure(background="white")
        self.entry_log.configure(disabledforeground="#a3a3a3")
        self.entry_log.configure(font="TkFixedFont")
        self.entry_log.configure(foreground="#000000")
        self.entry_log.configure(highlightbackground="#d9d9d9")
        self.entry_log.configure(highlightcolor="black")
        self.entry_log.configure(insertbackground="black")
        self.entry_log.configure(selectbackground="blue")
        self.entry_log.configure(selectforeground="white")

        self.boutton_log = tk.Button(top)
        self.boutton_log.place(relx=0.87, rely=0.962, height=24, width=67)
        self.boutton_log.configure(activebackground="#ececec")
        self.boutton_log.configure(activeforeground="#000000")
        self.boutton_log.configure(background="#d9d9d9")
        self.boutton_log.configure(command=envoyer_log)
        self.boutton_log.configure(disabledforeground="#a3a3a3")
        self.boutton_log.configure(foreground="#000000")
        self.boutton_log.configure(highlightbackground="#d9d9d9")
        self.boutton_log.configure(highlightcolor="black")
        self.boutton_log.configure(pady="0")
        self.boutton_log.configure(text='''OK''')

        self.label_entry = tk.Label(top)
        self.label_entry.place(relx=0.016, rely=0.962, height=21, width=44)
        self.label_entry.configure(background="#d9d9d9")
        self.label_entry.configure(disabledforeground="#a3a3a3")
        self.label_entry.configure(foreground="#000000")
        self.label_entry.configure(text='''Entrée :''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.016, rely=0.617, height=21, width=154)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI} -size 9 -slant italic")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Gyrfalcon - version 1.0''')

        self.log = tk.Text(top)
        self.log.place(relx=0.016, rely=0.69, relheight=0.259, relwidth=0.628)
        self.log.configure(background="white")
        self.log.configure(font="TkTextFont")
        self.log.configure(foreground="black")
        self.log.configure(highlightbackground="#d9d9d9")
        self.log.configure(highlightcolor="black")
        self.log.configure(insertbackground="black")
        self.log.configure(selectbackground="blue")
        self.log.configure(selectforeground="white")
        self.log.configure(wrap="word")

        self.options = tk.LabelFrame(top)
        self.options.place(relx=0.66, rely=0.69, relheight=0.256, relwidth=0.324)

        self.options.configure(relief='groove')
        self.options.configure(foreground="black")
        self.options.configure(text='''OPTIONS''')
        self.options.configure(background="#d9d9d9")

        self.option1 = tk.Button(self.options)
        self.option1.place(relx=0.1, rely=0.122, height=34, width=77
                , bordermode='ignore')
        self.option1.configure(activebackground="#ececec")
        self.option1.configure(activeforeground="#000000")
        self.option1.configure(background="#d9d9d9")
        self.option1.configure(command=option1)
        self.option1.configure(disabledforeground="#a3a3a3")
        self.option1.configure(foreground="#000000")
        self.option1.configure(highlightbackground="#d9d9d9")
        self.option1.configure(highlightcolor="black")
        self.option1.configure(pady="0")
        self.option1.configure(text='''Option 1''')

        self.option2 = tk.Button(self.options)
        self.option2.place(relx=0.547, rely=0.122, height=34, width=77
                , bordermode='ignore')
        self.option2.configure(activebackground="#ececec")
        self.option2.configure(activeforeground="#000000")
        self.option2.configure(background="#d9d9d9")
        self.option2.configure(command=option2)
        self.option2.configure(cursor="fleur")
        self.option2.configure(disabledforeground="#a3a3a3")
        self.option2.configure(foreground="#000000")
        self.option2.configure(highlightbackground="#d9d9d9")
        self.option2.configure(highlightcolor="black")
        self.option2.configure(pady="0")
        self.option2.configure(text='''Option 2''')

        self.option3 = tk.Button(self.options)
        self.option3.place(relx=0.1, rely=0.286, height=34, width=77
                , bordermode='ignore')
        self.option3.configure(activebackground="#ececec")
        self.option3.configure(activeforeground="#000000")
        self.option3.configure(background="#d9d9d9")
        self.option3.configure(command=option3)
        self.option3.configure(disabledforeground="#a3a3a3")
        self.option3.configure(foreground="#000000")
        self.option3.configure(highlightbackground="#d9d9d9")
        self.option3.configure(highlightcolor="black")
        self.option3.configure(pady="0")
        self.option3.configure(text='''Option 3''')

        self.option5 = tk.Button(self.options)
        self.option5.place(relx=0.1, rely=0.449, height=34, width=77
                , bordermode='ignore')
        self.option5.configure(activebackground="#ececec")
        self.option5.configure(activeforeground="#000000")
        self.option5.configure(background="#d9d9d9")
        self.option5.configure(command=option5)
        self.option5.configure(disabledforeground="#a3a3a3")
        self.option5.configure(foreground="#000000")
        self.option5.configure(highlightbackground="#d9d9d9")
        self.option5.configure(highlightcolor="black")
        self.option5.configure(pady="0")
        self.option5.configure(text='''Option 5''')

        self.option7 = tk.Button(self.options)
        self.option7.place(relx=0.1, rely=0.612, height=34, width=77
                , bordermode='ignore')
        self.option7.configure(activebackground="#ececec")
        self.option7.configure(activeforeground="#000000")
        self.option7.configure(background="#d9d9d9")
        self.option7.configure(command=option7)
        self.option7.configure(disabledforeground="#a3a3a3")
        self.option7.configure(foreground="#000000")
        self.option7.configure(highlightbackground="#d9d9d9")
        self.option7.configure(highlightcolor="black")
        self.option7.configure(pady="0")
        self.option7.configure(text='''Option 7''')

        self.option9 = tk.Button(self.options)
        self.option9.place(relx=0.1, rely=0.776, height=34, width=77
                , bordermode='ignore')
        self.option9.configure(activebackground="#ececec")
        self.option9.configure(activeforeground="#000000")
        self.option9.configure(background="#d9d9d9")
        self.option9.configure(command=option9)
        self.option9.configure(disabledforeground="#a3a3a3")
        self.option9.configure(foreground="#000000")
        self.option9.configure(highlightbackground="#d9d9d9")
        self.option9.configure(highlightcolor="black")
        self.option9.configure(pady="0")
        self.option9.configure(text='''Option 9''')

        self.option4 = tk.Button(self.options)
        self.option4.place(relx=0.547, rely=0.286, height=34, width=77
                , bordermode='ignore')
        self.option4.configure(activebackground="#ececec")
        self.option4.configure(activeforeground="#000000")
        self.option4.configure(background="#d9d9d9")
        self.option4.configure(command=option4)
        self.option4.configure(disabledforeground="#a3a3a3")
        self.option4.configure(foreground="#000000")
        self.option4.configure(highlightbackground="#d9d9d9")
        self.option4.configure(highlightcolor="black")
        self.option4.configure(pady="0")
        self.option4.configure(text='''Option 4''')

        self.option6 = tk.Button(self.options)
        self.option6.place(relx=0.547, rely=0.449, height=34, width=77
                , bordermode='ignore')
        self.option6.configure(activebackground="#ececec")
        self.option6.configure(activeforeground="#000000")
        self.option6.configure(background="#d9d9d9")
        self.option6.configure(command=option6)
        self.option6.configure(disabledforeground="#a3a3a3")
        self.option6.configure(foreground="#000000")
        self.option6.configure(highlightbackground="#d9d9d9")
        self.option6.configure(highlightcolor="black")
        self.option6.configure(pady="0")
        self.option6.configure(text='''Option 6''')

        self.option8 = tk.Button(self.options)
        self.option8.place(relx=0.547, rely=0.612, height=34, width=77
                , bordermode='ignore')
        self.option8.configure(activebackground="#ececec")
        self.option8.configure(activeforeground="#000000")
        self.option8.configure(background="#d9d9d9")
        self.option8.configure(command=option8)
        self.option8.configure(disabledforeground="#a3a3a3")
        self.option8.configure(foreground="#000000")
        self.option8.configure(highlightbackground="#d9d9d9")
        self.option8.configure(highlightcolor="black")
        self.option8.configure(pady="0")
        self.option8.configure(text='''Option 8''')

        self.option10 = tk.Button(self.options)
        self.option10.place(relx=0.547, rely=0.776, height=34, width=77
                , bordermode='ignore')
        self.option10.configure(activebackground="#ececec")
        self.option10.configure(activeforeground="#000000")
        self.option10.configure(background="#d9d9d9")
        self.option10.configure(command=option10)
        self.option10.configure(disabledforeground="#a3a3a3")
        self.option10.configure(foreground="#000000")
        self.option10.configure(highlightbackground="#d9d9d9")
        self.option10.configure(highlightcolor="black")
        self.option10.configure(pady="0")
        self.option10.configure(text='''Option 10''')

        # set default value at start
        now = datetime.now() # current date and time
        date_time = now.strftime("%d/%m/%y")	
        log("Le " + date_time)
        new()
        #blink test for detresse
        blink_circu()
        blink_neuro()
        blink_respi()

if __name__ == '__main__':
    vp_start_gui()





